# .github/workflows/mirror-json.yml

name: Mirror JSON Files

on:
  schedule:
    - cron: '0 * * * *' # 默认定时规则。可手动修改为其他值，如需完全动态，请使用 repository dispatch 或外部触发器
  workflow_dispatch:

jobs:
  mirror-json:
    runs-on: ubuntu-latest
    env:
      GH_MIRROR: ${{ vars.GH_MIRROR }}
      JSON_URLS: ${{ vars.JSON_URLS }}

    steps:
      - name: 检出仓库
        uses: actions/checkout@v3

      - name: 设置 Python 环境
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 安装依赖
        run: |
          pip install requests

      - name: 执行镜像处理脚本
        run: |
          python scripts/mirror_json.py

      - name: 提交并推送更改
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "更新 packages 目录"
          file_pattern: packages/*
      
      - name: 生成 release 名称和 tag
        id: generate_release_info
        run: |
          release_name="Release v$(date '+%Y%m%d%H%M%S')"
          tag_name="latest"

          echo "release_name=$release_name" >> $GITHUB_OUTPUT
          echo "tag_name=$tag_name" >> $GITHUB_OUTPUT
      
      - name: 收集 packages 文件列表
        id: collect_files
        run: |
          files=$(ls packages/*)
          joined_files=$(echo "$files" | paste -sd "," -)
          echo "package_files=$joined_files" >> $GITHUB_OUTPUT
      
      - name: 强制更新 latest tag 到当前提交
        run: |
          # 删除远程和本地的 latest tag（如果存在）
          if git rev-parse refs/tags/${{ steps.generate_release_info.outputs.tag_name }} > /dev/null 2>&1; then
            git tag -d ${{ steps.generate_release_info.outputs.tag_name }}
            git push origin --delete ${{ steps.generate_release_info.outputs.tag_name }} || echo "Remote tag not found, skipping delete."
          fi

          # 创建新的 tag 并推送到远程
          git tag ${{ steps.generate_release_info.outputs.tag_name }}
          git push -f origin ${{ steps.generate_release_info.outputs.tag_name }}

      - name: 创建/更新 Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PUSH_TOKEN }}
          RELEASE_NAME: ${{ steps.generate_release_info.outputs.release_name }}
        with:
          name: ${{ env.RELEASE_NAME }}
          tag_name: ${{ steps.generate_release_info.outputs.tag_name }}
          draft: false
          prerelease: false
          files: ${{ steps.collect_files.outputs.package_files }}