# .github/workflows/mirror-json.yml

name: Mirror JSON Files

on:
  schedule:
    - cron: '0 0 * * *' # 默认定时规则。可手动修改为其他值，如需完全动态，请使用 repository dispatch 或外部触发器
  workflow_dispatch:

jobs:
  mirror-json:
    runs-on: ubuntu-latest
    env:
      GH_MIRROR: ${{ vars.GH_MIRROR }}
      JSON_URLS: ${{ vars.JSON_URLS }}

    steps:
      - name: 检出仓库
        uses: actions/checkout@v3

      - name: 设置 Python 环境
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 安装依赖
        run: |
          pip install requests

      - name: 执行镜像处理脚本
        run: |
          python scripts/mirror_json.py

      - name: 提交并推送更改
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "更新 packages 目录"
          file_pattern: packages/*
      
      - name: 收集 packages 文件列表
        id: collect_files
        run: |
          # 获取 packages 下的所有文件名（以换行分隔）
          files=$(ls packages/*)
          
          # 用逗号连接成字符串，用于后续传递给 create-release
          joined_files=$(echo "$files" | paste -sd "," -)
          
          # 输出到 outputs 供后续步骤使用
          echo "files=$joined_files"
          echo "::set-output::name=package_files::$joined_files"

      - name: 创建 Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PUSH_TOKEN }}
        with:
          name: Release v$(date '+%Y%m%d%H%M%S')
          draft: false
          prerelease: false
          files: ${{ steps.collect_files.outputs.package_files }}